services:
  - type: web
    name: c-hashtag-ttyd-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: "8080"